name = "Magnetar"
author = "mxxntype"
version = "3.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1cbd66159ab80f39a00172dcfe40232b175fb9d999b92db4f8095b614aeaccd3"

[versions]
minecraft = "1.19.2"
quilt = "0.19.1"
