name = "Magnetar"
author = "mxxntype"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75f80dd1f1cfaac6ba21813ec387a17d69b569a18f4443b2d552def5eda5f93c"

[versions]
minecraft = "1.19.2"
quilt = "0.19.1"
